export default [
    {
      id: 221,
      name: "Shopping list",
      created: "May 20, 2021",
      category: "Task",
      content: "Tomatoes, bread",
      date: "April 20, 2021",
      archived: false,
    },
    {
      id: 222,
      name: "The theory of evolushion",
      created: "March 20, 2021",
      category: "Random Thought",
      content: "Coffe bra",
      date: "April 20, 2021",
      archived: false,
    },
    {
      id: 223,
      name: "New Features",
      created: "June 20, 2021",
      category: "Idea",
      content: "TV show",
      date: "June 20, 2021",
      archived: false,
    },
    {
      id: 224,
      name: "Shopping list",
      created: "March 20, 2021",
      category: "Quote",
      content: "Tomatoes, bread",
      date: "April 20, 2021",
      archived: false,
    },
    {
      id: 225,
      name: "The theory of evolushion",
      created: "June 20, 2021",
      category: "Random Thought",
      content: "Coffe bra",
      date: "June 20, 2021",
      archived: false,
    },
    {
      id: 226,
      name: "New Features",
      created: "August 20, 2021",
      category: "Idea",
      content: "TV show",
      date: "August 20, 2021",
      archived: false,
    },
    {
      id: 227,
      name: "Newtures",
      created: "August 20, 2021",
      category: "Idea",
      content: "TV show",
      date: "August 20, 2021",
      archived: false,
    },
    {
      id: 228,
      name: "New Feaes",
      created: "August 20, 2021",
      category: "Idea",
      content: "TV show",
      date: "August 20, 2021",
      archived: false,
    },
];
